### ISSUE TITLE
Quarkus Security still relies on javax artefact

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus-security#11]
Quarkus Security has a dependency on `javax.enterprise:cdi-api` whereas all Quarkus extensions have a dependency on `jakarta.enterprise:jakarta.enterprise.cdi-api`.

So duplicated class files are in the classpath.

**Comment by sberyozkin** [comment]
@stuartwdouglas And this one definitely can be closed now, @loicmathieu please close if you agree :-)

**Comment by loicmathieu** [comment]
Yes, it's no more the case so closing it.
