### ISSUE TITLE
Certificate is null if `quarkus.http.ssl.client-auth` property is in a profile

### ISSUE THREAD

**Issue by mcsweeneyjm** [quarkusio/quarkus-security#15]
When attempting to do MTLS auth in Quarkus, the `SecurityIdentity` does not have the certificate information if I have the `quarkus.http.ssl.client-auth:request` property in a profile in `application.properties`. If I move this property out to the top-level outside of a profile, the certificate will load. I'm also testing this in Docker, so that might be relevant as well.

link to a reproducer here: https://github.com/mcsweeneyjm/quarkus-mtls-issue

**Comment by sberyozkin** [comment]
@mcsweeneyjm Can you please move to the Quarkus project ?

**Comment by mcsweeneyjm** [comment]
done! opened https://github.com/quarkusio/quarkus/issues/16694
