### ISSUE TITLE
quarkus.oidc.authentication.redirect-path

### ISSUE THREAD

**Issue by skumaravelan** [quarkusio/quarkus-security#39]
I have question regarding redirect_uri full path, How could we configure to have full return url. quarkus
Config : oidc.authentication.redirect-path
Always the request path is getting concatenated with url that is configured. is there any option to set full path.

**Comment by michalvavrik** [comment]
This is wrong place, this project is for API only. Please raise your question here: https://github.com/quarkusio/quarkus/discussions

**Comment by sberyozkin** [comment]
This is now supported in Quarkus OIDC
