### ISSUE TITLE
Duplicate authentication exception classes

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus-security#5]
There are 2 exception classes, `AuthenticaionFailedException` and `UnauthorizedException` which I believe are used for 401.

**Comment by sberyozkin** [comment]
CC @stuartwdouglas

**Comment by stuartwdouglas** [comment]
AuthenticationFailed is when you do not have a valid user because the credentials were wrong (or no credentials). UnauthorizedException is when you do have a valid user and permission is denied.

**Comment by stuartwdouglas** [comment]
Actually there is also io.quarkus.security.ForbiddenException, one of these needs to go away

**Comment by sberyozkin** [comment]
@stuartwdouglas yea, `UnauthroizedException` is 401 in JAX-RS

**Comment by sberyozkin** [comment]
@stuartwdouglas Perhaps `AuthenticationFailedException` can go ? It is much easier to read from it what it means :-), I've found it a bit misleading that HTTP 401 is actually treated as Unauthorized (even without JAX-RS) but at least the JAX-RS users will know what it means. I've no strong preferences though so please remove the one you prefer. I can then follow up at the Quarkus side (I'll traveling tomorrow late afternoon and be back on Tue morning though)

**Comment by stuartwdouglas** [comment]
They actually all have different meanings:
AuthenticationFailedException -> Authentication was attempted, but it failed
UnauthorizedException -> You need to authenticate to access this resource
ForbiddenException -> You do not have permission to access this resource

**Comment by stuartwdouglas** [comment]
AuthenticationFailedException is specific to the auth layer and is a way of specifying failure.

**Comment by sberyozkin** [comment]
@stuartwdouglas sure one can assume it, but there is no way to differentiate at the HTTP status level. When a user attempts to access a secured resource without some credentials or with the wrong ones, it is 401. 
Do you think it could be useful at the Quarkus level to differentiate ? If so then please close the issue, I'll be fine with it. I guess the logging can definitely be more specific, so I can see some benefit....Thanks

**Comment by stuartwdouglas** [comment]
I think this is fine. AuthenticationFailedException is not a user facing exception unless you are writing a HTTP Authenticator. It is used to specify a very specific failure case (i.e. invalid credentials).
